notifications:
  email:
    on_failure: always
    on_success: change
sudo: required
dist: trusty
language: cpp
compiler:
  - clang
  - gcc
branches:
  only:
    - master
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.6
    packages:
    - gcc
    - g++
    - clang
script:
- mkdir build
- cd build
- cmake .. && make
- src/uber3d/uber_test
